# Generated by Django 5.2.6 on 2025-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию",
                null=True,
                upload_to="image",
                verbose_name="Фото",
            ),
        ),
    ]
