# Generated by Django 5.2.6 on 2025-10-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию",
                null=True,
                upload_to="images",
                verbose_name="Фото",
            ),
        ),
    ]
